### ISSUE TITLE
[FEEDBACK]Isn't this styleguide encouraging anemic domain models?

### ISSUE THREAD

**Issue by gbrennon** [phalt/django-api-domains#16]
Hey phalt, how are u doing?

So... I'm currently following ur style guide on some projects that I'm currently working on and I've been thinking... Isn't this style guide encouraging anemic domain models?

Because you threaten the apps as our "domains" and don't write any domain classes and don't even write some mapping functions to map from domain to model and vice-versa.

You also say to people keep business logic on the service layer. But let's say that I have a `Dog` domain class and I want to implement the `bark` method. Following this guide I would implement this on the service layer and, lets say, do something like this:
```python
class DogService:
    @staticmethod
    def bark(dog):
        return 'woof'
```

Would it be more meaningful to be written down like this?
```python
class Dog:
    def bark(self):
        return 'woof'
```

**Comment by gbrennon** [comment]
Sorry, I've found the answer in an old issue. 
This is on #1

**Comment by phalt** [comment]
Hey @gbrennon thanks for reading my style guide! yes, issue #1 clarifies some of this. I have pinned the issue now so people can find it easier.
