### ISSUE TITLE
[QUESTION] How do you handle models that are used in more than 1 domain/app?

### ISSUE THREAD

**Issue by simkimsia** [phalt/django-api-domains#26]
Sorry I change your type to question.

in boundedcontexts https://martinfowler.com/bliki/BoundedContext.html using the same example as Fowler

![diagram](https://martinfowler.com/bliki/images/boundedContext/sketch.png)

You can have Customer and Product in more than 1 boundedcontexts. Since in your styleguide, your first two goals at https://phalt.github.io/django-api-domains/ are:

> 1. Treat Django's apps like software domains.
> 2. Extend Django's apps implementation to support strong bounded context patterns between domains.

Using Fowler's example, where would you create the Django model for Customer or Product, if the Support is an Django app and sales is another Django app?

**Comment by phalt** [comment]
In a Django context like this, my immediate thought is that I have two (basically) identical models in the respective apps, and a sync mechanism to keep them in sync, either as a background tasks, or on demand. I would create them as a normal model in each respective Django app, giving them a name like `SalesContextCustomer` and `SupportContextCustomer`, for example. They should ideally share the same UUID so you can link them together.

**Comment by simkimsia** [comment]
So you will have two different Django models and therefore two different datatables, but the same Customer can exist in both with the same UUID.

Correct?

**Comment by phalt** [comment]
Yeah, this is in essence, what Martin Fowler's bounded contexts is all about.

They are kept in sync too.

**Comment by simkimsia** [comment]
Thank you. Closing this
